# Generated by Django 3.2.20 on 2023-08-03 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['type', 'title']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=25)),
                ('number_of_items', models.IntegerField(default=1)),
                ('booking_date', models.DateField()),
                ('delivery', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=100)),
                ('booking_time', models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')], default=1)),
                ('booked_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_item', to='booking.menuitem')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
    ]
