# Generated by Django 3.2.20 on 2023-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230803_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookitem',
            old_name='delivery',
            new_name='home_delivery',
        ),
        migrations.AddField(
            model_name='bookitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
