# Generated by Django 3.2.20 on 2023-08-04 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_auto_20230804_1203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookItem',
            new_name='Bookings',
        ),
    ]
