# Generated by Django 3.2.20 on 2023-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_bookings_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='type',
        ),
    ]
